using System.Collections.Generic;
using UnityEngine;

namespace Restless.Dream.Procedural
{
    /// <summary>
    /// Abstract graph of a run — nodes and edges, no geometry yet.
    /// Generated by RunGraphGenerator, consumed by RoomAssembler.
    /// </summary>
    public class RunGraph
    {
        public List<GraphNode> Nodes = new();
        public List<GraphEdge> Edges = new();

        public GraphNode Entrance => Nodes.Count > 0 ? Nodes[0] : null;
        public GraphNode Exit     { get; set; }

        public void AddEdge(GraphNode a, GraphNode b)
        {
            Edges.Add(new GraphEdge(a, b));
            a.Neighbours.Add(b);
            b.Neighbours.Add(a);
        }

        public List<GraphNode> GetNeighbours(GraphNode node) => node.Neighbours;
    }

    public class GraphNode
    {
        public int        Index;
        public RoomType   Type;
        public RoomSize   PreferredSize;
        public float      DangerHint;     // 0-1, passed to room selection
        public bool       MustHaveFragment;
        public bool       IsEntrance;
        public bool       IsExit;

        public List<GraphNode> Neighbours = new();
        public RoomController  PlacedRoom;  // filled by assembler

        public GraphNode(int index, RoomType type, RoomSize size = RoomSize.Medium)
        {
            Index         = index;
            Type          = type;
            PreferredSize = size;
        }
    }

    public class GraphEdge
    {
        public GraphNode A;
        public GraphNode B;
        public GraphEdge(GraphNode a, GraphNode b) { A = a; B = b; }
    }
}
